### PR TITLE
Conflict resolution ui

### PR DESCRIPTION
**Pull request by samanpwbb**
This branch reworks the conflict resolution UI:

- Moved the conflict resolution UI out of a modal and into a sidebar overlay
- Clicking on conflicting features centers +highlights features.
- After resolving one feature, next feature is automatically highlighted.
- Save button is disabled until all conflicts are resolved.

In addition, I couldn't restrain myself from righting some design/css wrongs a younger version of myself made a couple years ago in iD.

I also merged master, sorry for the sloppiness that introduced. 

@bhousel could you give this a review? Let me know what you think of the design adjustments, and I wouldn't be surprised if the code could be significantly cleaned up, I'm not that experienced with D3.

cc: @jfirebaugh @aaronlidman

### CODE REVIEW

**Comment by jfirebaugh** [comment]
@samanpwbb @bhousel Not sure what happened here but this PR has a bunch of irrelevant commits. Let's switch to working in branches / PRs in the main repo and close it out.

**Comment by samanpwbb** [comment]
@jfirebaugh my branch is a fork of @bhousel's, but I merged with openstreetmap/master -- what should I do next here? Just directly make a PR against openstreetmap/master?

**Comment by jfirebaugh** [comment]
Yes, please reroll https://github.com/openstreetmap/iD/pull/2489 using a `conflict-resolution` branch in the main repository. Don't worry about making a separate branch. One feature, one branch.

@bhousel please use branches in osm/iD for future work, for easier collaboration.

**Comment by samanpwbb** [comment]
Replaced by https://github.com/openstreetmap/iD/pull/2525

**Pull request closed without merging**
